version: '2.1'

services:

  # datascience Notebook
  dsnb:
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: start.sh jupyter notebook
    #--NotebookApp.base_url=/home/joyvan/work
    env_file:
        - .env
