version: '2.1'

services:

  # datascience Notebook
  dsnb:
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: start-notebook.sh --NotebookApp.base_url=/home/joyvan/work
    env_file:
        - .env
